# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7505263a9d2f7ac54fdebdc95a43505fa9e7b5a56cc680f7ace513f17f5f69d4fb84b905442b903cd779a8ec002cc6767e505882d140970a06c40b1c431966ad

test:
  secret_key_base: c7aff47947ba7a1ed94e74a09de5cc49f973acb19f50823c61077bf501e637e1038df00ffd0123bd402428cc939c6e1bdae5ec156dc6ecda7cca56d1de247d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
